# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Bundle app source
COPY src ./src
COPY .env.template ./

# Expose no port since this is stdio-based

# Default command
CMD ["node", "src/index.js"]
